In [1]:
import numpy as np

In [2]:
a = np.array(range(20))

In [3]:
removal = np.random.randint(0, 20, size=(np.random.randint(3,15)))
b = np.delete(a, removal)
b, removal

(array([ 0,  1,  2,  3,  4,  6,  7,  9, 11, 12, 13, 14, 16, 17, 18, 19]),
 array([15,  5, 10,  8]))

In [4]:
b[1:] - b[:-1]

array([1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1])

In [5]:
difference = [0 for i in range(len(a))]
last_difference = 0

for label in np.sort(a):
    if label in removal:
        last_difference += 1

    difference[label] = last_difference

for idx, label in enumerate(b):
    b[idx] -= difference[label]

In [6]:
b[1:] - b[:-1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])